Serverspec test
shino-taira/raisetech-cloudformation pull request #3
Opened 2023-04-28 17:37 UTC by shino-taira

2023-04-28 17:43 UTC, MasatoshiMizumoto requested changes
画像でもいいのですが、元の出力が文字情報なので、
コードブロックで書いたmarkdownで提出いただきたいです！

2023-04-28 18:12 UTC, shino-taira commented
<img width="484" alt="スクリーンショット 2023-04-29 3 10 50" src="https://user-images.githubusercontent.com/98676389/235222333-1573b187-c384-45f1-a550-d941228fc9a1.png">
見ながらやっているのですがうまくいかず、このことで合っていますか？

2023-04-28 18:24 UTC, shino-taira commented
<img width="829" alt="スクリーンショット 2023-04-29 3 23 10" src="https://user-images.githubusercontent.com/98676389/235224639-e8c00f23-9846-4a29-af07-6129c349fa20.png">

2023-04-29 03:51 UTC, MasatoshiMizumoto commented
おや、拡張子は？

2023-04-29 04:07 UTC, shino-taira commented
なるほど！READ.meのように書くためには、.md(マークダウン)を入れなければいけなかったんですね！拡張子を入れて、コードブロックで書いたマークダウンで記述できました！確認お願いいたします。

2023-04-29 04:20 UTC, MasatoshiMizumoto commented
内容としてはOKですが、このリポジトリはポートフォリオにする予定ですか？
その場合は関係者じゃない人が何をしたのか分かるようにする必要があるので、例えばPRのコメントのメンテなど整備してほしいです！

2023-04-29 04:40 UTC, shino-taira commented
ありがとうございます。
PRのコメントのメンテとは、コメントの方法でしょうか？
PRを申請する時に確認してほしいことなどの詳細をつけるなど、でしょうか？

2023-04-29 05:35 UTC, MasatoshiMizumoto commented
PRのタイトルや親コメントの整備をしてほしいです！
なぜこのPRが発行されたのか、関係者外の人が見ても分かるように、がポイントです！

2023-04-29 05:52 UTC, shino-taira commented
わかりました！ありがとうございます！

2023-04-29 08:06 UTC, MasatoshiMizumoto commented
今回の場合だとPRのタイトルは第11回課題提出とか書く人が多いです！

2023-04-29 08:09 UTC, shino-taira commented
なるほど。PRのタイトルは第11回課題提出で、変更点を親コメントに記述というのが一般的でしょうか？

2023-04-30 05:19 UTC, MasatoshiMizumoto approved these changes
LGTM!!

2023-04-30 09:30 UTC, shino-taira commented
ありがとうございます。マージします！

2023-04-30 09:34 UTC, merged